### ISSUE TITLE
Provide a Code Example

### ISSUE THREAD

**Issue by mike-zarandona** [jballe/grunt-ftpdownload#2]
Would you provide a usage example for this plugin?  I'd love to use it, but I'm having some trouble getting started.  Thanks!

**Comment by jballe** [comment]
Sure, I used it this way, however, I have heard that the package might have some issues with newer versions of the jsftp

```javascript
grunt.config.merge({
		ftpdownload: {
		    uploadsfromaspnixtest: {
		        auth: {
		            host: serverhosname,
		            username: ftpuser,
		            password: ftppassword
		        },
		        src: serverdir,
		        dest: localdir
		}
});
```

Do you get some kind of errors?

**Comment by mike-zarandona** [comment]
No errors, it worked perfectly!  Thanks so much, I've been looking all over the web for an easy Grunt.js plugin for FTP downloads.  Cheers!
